apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app
  namespace: budget-app
  labels:
    app: budget-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app
  template:
    metadata:
      labels:
        app: budget-app
    spec:
      imagePullSecrets:
        - name: regcred  # <- reference to Docker Hub secret
      containers:
        - name: web
          image: technicalaisha/budget-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: budget-app-config
                  key: RAILS_ENV
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: budget-app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budget-app-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: budget-app-secret
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"

